<template><div><h1 id="_4-centos搭建docker" tabindex="-1"><a class="header-anchor" href="#_4-centos搭建docker" aria-hidden="true">#</a> 4.Centos搭建docker</h1>
<h2 id="_4-1-安装docker" tabindex="-1"><a class="header-anchor" href="#_4-1-安装docker" aria-hidden="true">#</a> 4.1.安装docker</h2>
<h3 id="_4-1-1-在线安装docker" tabindex="-1"><a class="header-anchor" href="#_4-1-1-在线安装docker" aria-hidden="true">#</a> 4.1.1.在线安装docker</h3>
<h3 id="_4-1-2-二进制包安装docker" tabindex="-1"><a class="header-anchor" href="#_4-1-2-二进制包安装docker" aria-hidden="true">#</a> 4.1.2.二进制包安装docker</h3>
<h2 id="_4-2-docker启动故障解决" tabindex="-1"><a class="header-anchor" href="#_4-2-docker启动故障解决" aria-hidden="true">#</a> 4.2.docker启动故障解决</h2>
<h2 id="_4-3-docker容器可视化" tabindex="-1"><a class="header-anchor" href="#_4-3-docker容器可视化" aria-hidden="true">#</a> 4.3.docker容器可视化</h2>
<h2 id="_4-4-搭建docke私服" tabindex="-1"><a class="header-anchor" href="#_4-4-搭建docke私服" aria-hidden="true">#</a> 4.4.搭建docke私服</h2>
<h2 id="_4-4-1搭建docke官方私服-不带有用户名和密码校验" tabindex="-1"><a class="header-anchor" href="#_4-4-1搭建docke官方私服-不带有用户名和密码校验" aria-hidden="true">#</a> 4.4.1搭建docke官方私服（不带有用户名和密码校验）</h2>
<h2 id="_4-4-2搭建docke官方私服-带有用户名和密码校验" tabindex="-1"><a class="header-anchor" href="#_4-4-2搭建docke官方私服-带有用户名和密码校验" aria-hidden="true">#</a> 4.4.2搭建docke官方私服（带有用户名和密码校验）</h2>
<h2 id="_4-4-3-搭建harbor私服" tabindex="-1"><a class="header-anchor" href="#_4-4-3-搭建harbor私服" aria-hidden="true">#</a> 4.4.3.搭建harbor私服</h2>
<h3 id="_4-4-3-1-harbor简介" tabindex="-1"><a class="header-anchor" href="#_4-4-3-1-harbor简介" aria-hidden="true">#</a> 4.4.3.1.harbor简介</h3>
<h3 id="_4-4-3-2-搭建docker-compose" tabindex="-1"><a class="header-anchor" href="#_4-4-3-2-搭建docker-compose" aria-hidden="true">#</a> 4.4.3.2.搭建docker-compose</h3>
<h3 id="_4-4-3-3-安装harbor" tabindex="-1"><a class="header-anchor" href="#_4-4-3-3-安装harbor" aria-hidden="true">#</a> 4.4.3.3.安装harbor</h3>
<h2 id="_4-5-docker官方私服可视化" tabindex="-1"><a class="header-anchor" href="#_4-5-docker官方私服可视化" aria-hidden="true">#</a> 4.5.docker官方私服可视化</h2>
<h3 id="_4-5-1docker-registry-web方案" tabindex="-1"><a class="header-anchor" href="#_4-5-1docker-registry-web方案" aria-hidden="true">#</a> 4.5.1docker-registry-web方案</h3>
<h2 id="_4-6-制作docker镜像并上传到私服" tabindex="-1"><a class="header-anchor" href="#_4-6-制作docker镜像并上传到私服" aria-hidden="true">#</a> 4.6.制作docker镜像并上传到私服</h2>
<h3 id="_4-6-1-制作dokcer镜像" tabindex="-1"><a class="header-anchor" href="#_4-6-1-制作dokcer镜像" aria-hidden="true">#</a> 4.6.1.制作Dokcer镜像</h3>
<h3 id="_4-6-2-上传本地jdk镜像到私服" tabindex="-1"><a class="header-anchor" href="#_4-6-2-上传本地jdk镜像到私服" aria-hidden="true">#</a> 4.6.2.上传本地jdk镜像到私服</h3>
<h2 id="_4-7-docker中安装常用软件" tabindex="-1"><a class="header-anchor" href="#_4-7-docker中安装常用软件" aria-hidden="true">#</a> 4.7.Docker中安装常用软件</h2>
<h3 id="_4-7-1-docker安装mysql" tabindex="-1"><a class="header-anchor" href="#_4-7-1-docker安装mysql" aria-hidden="true">#</a> 4.7.1.Docker安装mysql</h3>
<h3 id="_4-7-2-docker中安装consul" tabindex="-1"><a class="header-anchor" href="#_4-7-2-docker中安装consul" aria-hidden="true">#</a> 4.7.2.Docker中安装consul</h3>
<h3 id="_4-7-3-docker容器中安装vim" tabindex="-1"><a class="header-anchor" href="#_4-7-3-docker容器中安装vim" aria-hidden="true">#</a> 4.7.3.Docker容器中安装vim</h3>
<h3 id="_4-7-3-docker安装elk" tabindex="-1"><a class="header-anchor" href="#_4-7-3-docker安装elk" aria-hidden="true">#</a> 4.7.3.docker安装elk</h3>
</div></template>
