#Apollo配置中心相关,其他所有配置都去Apollo配置中心中去获取
app:
  id: springcloud-eureka
apollo:
  bootstrap:
    enabled: true
    namespaces: application #多个namespaces之间使用,隔开
spring:
  cloud:
    inetutils:
      timeout-seconds: 5 # 设置网络超时
      ignored-interfaces: ## 忽略网卡
        - VMware Virtual Ethernet Adapter for VMnet1
        - VMware Virtual Ethernet Adapter for VMnet8
  devtools:
    restart:
      enabled: false
server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoint:
    restart:
      enabled: true