<template><div><h1 id="_1-安装linux操作系统" tabindex="-1"><a class="header-anchor" href="#_1-安装linux操作系统" aria-hidden="true">#</a> 1.安装Linux操作系统</h1>
<h2 id="_1-1-linux重要目录介绍" tabindex="-1"><a class="header-anchor" href="#_1-1-linux重要目录介绍" aria-hidden="true">#</a> 1.1.Linux重要目录介绍</h2>
<h2 id="_1-2-centos镜像下载" tabindex="-1"><a class="header-anchor" href="#_1-2-centos镜像下载" aria-hidden="true">#</a> 1.2.Centos镜像下载</h2>
<h2 id="_1-3-安装前vmaware相关设置" tabindex="-1"><a class="header-anchor" href="#_1-3-安装前vmaware相关设置" aria-hidden="true">#</a> 1.3.安装前Vmaware相关设置</h2>
<h2 id="_1-3-安装时分区大小设置" tabindex="-1"><a class="header-anchor" href="#_1-3-安装时分区大小设置" aria-hidden="true">#</a> 1.3.安装时分区大小设置</h2>
<h1 id="_2-linux操作系统初始设置" tabindex="-1"><a class="header-anchor" href="#_2-linux操作系统初始设置" aria-hidden="true">#</a> 2.Linux操作系统初始设置</h1>
<h2 id="_2-1-配置静态ip地址" tabindex="-1"><a class="header-anchor" href="#_2-1-配置静态ip地址" aria-hidden="true">#</a> 2.1.配置静态IP地址</h2>
<h2 id="_2-2-解决远程连接无法连接的问题" tabindex="-1"><a class="header-anchor" href="#_2-2-解决远程连接无法连接的问题" aria-hidden="true">#</a> 2.2.解决远程连接无法连接的问题</h2>
<h2 id="_2-3-设置系统环境变量" tabindex="-1"><a class="header-anchor" href="#_2-3-设置系统环境变量" aria-hidden="true">#</a> 2.3.设置系统环境变量</h2>
<h2 id="_2-4-安装curl" tabindex="-1"><a class="header-anchor" href="#_2-4-安装curl" aria-hidden="true">#</a> 2.4.安装curl</h2>
<h2 id="_2-5-配置yml源" tabindex="-1"><a class="header-anchor" href="#_2-5-配置yml源" aria-hidden="true">#</a> 2.5.配置yml源</h2>
<h2 id="_2-6-安装常用基础系统软件" tabindex="-1"><a class="header-anchor" href="#_2-6-安装常用基础系统软件" aria-hidden="true">#</a> 2.6.安装常用基础系统软件</h2>
<h1 id="_3-搭建基础开发环境" tabindex="-1"><a class="header-anchor" href="#_3-搭建基础开发环境" aria-hidden="true">#</a> 3.搭建基础开发环境</h1>
<h2 id="_3-1-安装jdk" tabindex="-1"><a class="header-anchor" href="#_3-1-安装jdk" aria-hidden="true">#</a> 3.1.安装jdk</h2>
<h2 id="_3-2-安装maven" tabindex="-1"><a class="header-anchor" href="#_3-2-安装maven" aria-hidden="true">#</a> 3.2.安装maven</h2>
<h2 id="_3-3-安装mysql" tabindex="-1"><a class="header-anchor" href="#_3-3-安装mysql" aria-hidden="true">#</a> 3.3.安装mysql</h2>
<h1 id="_4-centos搭建docker" tabindex="-1"><a class="header-anchor" href="#_4-centos搭建docker" aria-hidden="true">#</a> 4.Centos搭建docker</h1>
<h2 id="_4-1-安装docker" tabindex="-1"><a class="header-anchor" href="#_4-1-安装docker" aria-hidden="true">#</a> 4.1.安装docker</h2>
<h2 id="_4-2-docker启动故障解决" tabindex="-1"><a class="header-anchor" href="#_4-2-docker启动故障解决" aria-hidden="true">#</a> 4.2.docker启动故障解决</h2>
<h2 id="_4-3-docker容器可视化" tabindex="-1"><a class="header-anchor" href="#_4-3-docker容器可视化" aria-hidden="true">#</a> 4.3.docker容器可视化</h2>
<h2 id="_4-4-搭建docke私服" tabindex="-1"><a class="header-anchor" href="#_4-4-搭建docke私服" aria-hidden="true">#</a> 4.4.搭建docke私服</h2>
<h2 id="_4-4-1搭建docke官方私服-不带有用户名和密码校验" tabindex="-1"><a class="header-anchor" href="#_4-4-1搭建docke官方私服-不带有用户名和密码校验" aria-hidden="true">#</a> 4.4.1搭建docke官方私服（不带有用户名和密码校验）</h2>
<h2 id="_4-4-2搭建docke官方私服-带有用户名和密码校验" tabindex="-1"><a class="header-anchor" href="#_4-4-2搭建docke官方私服-带有用户名和密码校验" aria-hidden="true">#</a> 4.4.2搭建docke官方私服（带有用户名和密码校验）</h2>
<h2 id="_4-4-3-搭建harbor私服" tabindex="-1"><a class="header-anchor" href="#_4-4-3-搭建harbor私服" aria-hidden="true">#</a> 4.4.3.搭建harbor私服</h2>
<h2 id="_4-5-docker官方私服可视化" tabindex="-1"><a class="header-anchor" href="#_4-5-docker官方私服可视化" aria-hidden="true">#</a> 4.5.docker官方私服可视化</h2>
<h2 id="_4-6-制作docker镜像并上传到私服" tabindex="-1"><a class="header-anchor" href="#_4-6-制作docker镜像并上传到私服" aria-hidden="true">#</a> 4.6.制作docker镜像并上传到私服</h2>
<h2 id="_4-7-docker中安装常用软件" tabindex="-1"><a class="header-anchor" href="#_4-7-docker中安装常用软件" aria-hidden="true">#</a> 4.7.Docker中安装常用软件</h2>
<h1 id="_5-centos搭建rancher" tabindex="-1"><a class="header-anchor" href="#_5-centos搭建rancher" aria-hidden="true">#</a> 5.Centos搭建Rancher</h1>
<h1 id="_6-centos搭建minikube" tabindex="-1"><a class="header-anchor" href="#_6-centos搭建minikube" aria-hidden="true">#</a> 6.Centos搭建Minikube</h1>
<h2 id="_6-1-minikube介绍" tabindex="-1"><a class="header-anchor" href="#_6-1-minikube介绍" aria-hidden="true">#</a> 6.1.minikube介绍</h2>
<h2 id="_6-2-版本说明" tabindex="-1"><a class="header-anchor" href="#_6-2-版本说明" aria-hidden="true">#</a> 6.2.版本说明</h2>
<h2 id="_6-3-开启vmware虚拟化" tabindex="-1"><a class="header-anchor" href="#_6-3-开启vmware虚拟化" aria-hidden="true">#</a> 6.3.开启Vmware虚拟化</h2>
<h2 id="_6-4-安装kubectl" tabindex="-1"><a class="header-anchor" href="#_6-4-安装kubectl" aria-hidden="true">#</a> 6.4.安装kubectl</h2>
<h2 id="_6-5-安装minikube" tabindex="-1"><a class="header-anchor" href="#_6-5-安装minikube" aria-hidden="true">#</a> 6.5.安装minikube</h2>
<h2 id="_6-6-使用阿里云加速docker-hub" tabindex="-1"><a class="header-anchor" href="#_6-6-使用阿里云加速docker-hub" aria-hidden="true">#</a> 6.6.使用阿里云加速docker hub</h2>
<h2 id="_6-7-启动minikube" tabindex="-1"><a class="header-anchor" href="#_6-7-启动minikube" aria-hidden="true">#</a> 6.7.启动minikube</h2>
<h2 id="_6-8-minikube常用命令" tabindex="-1"><a class="header-anchor" href="#_6-8-minikube常用命令" aria-hidden="true">#</a> 6.8.minikube常用命令</h2>
<h1 id="_7-kubeadm搭建kubernetes" tabindex="-1"><a class="header-anchor" href="#_7-kubeadm搭建kubernetes" aria-hidden="true">#</a> 7.kubeadm搭建Kubernetes</h1>
<h2 id="_7-1-特别说明" tabindex="-1"><a class="header-anchor" href="#_7-1-特别说明" aria-hidden="true">#</a> 7.1.特别说明</h2>
<h2 id="_7-2-所有节点设置对应主机名" tabindex="-1"><a class="header-anchor" href="#_7-2-所有节点设置对应主机名" aria-hidden="true">#</a> 7.2.所有节点设置对应主机名</h2>
<h2 id="_7-3-所有节点修改hosts" tabindex="-1"><a class="header-anchor" href="#_7-3-所有节点修改hosts" aria-hidden="true">#</a> 7.3.所有节点修改hosts</h2>
<h2 id="_7-4-所有节点关闭selinux" tabindex="-1"><a class="header-anchor" href="#_7-4-所有节点关闭selinux" aria-hidden="true">#</a> 7.4.所有节点关闭SELinux</h2>
<h2 id="_7-5-所有节点关闭防火墙" tabindex="-1"><a class="header-anchor" href="#_7-5-所有节点关闭防火墙" aria-hidden="true">#</a> 7.5.所有节点关闭防火墙</h2>
<h2 id="_7-6-所有节点安装docker" tabindex="-1"><a class="header-anchor" href="#_7-6-所有节点安装docker" aria-hidden="true">#</a> 7.6.所有节点安装docker</h2>
<h2 id="_7-7-所有节点安装k8s所需组件" tabindex="-1"><a class="header-anchor" href="#_7-7-所有节点安装k8s所需组件" aria-hidden="true">#</a> 7.7.所有节点安装k8s所需组件</h2>
<h2 id="_7-8-所有节点启动kubelet和docker" tabindex="-1"><a class="header-anchor" href="#_7-8-所有节点启动kubelet和docker" aria-hidden="true">#</a> 7.8.所有节点启动kubelet和docker</h2>
<h2 id="_7-9-所有关闭swap" tabindex="-1"><a class="header-anchor" href="#_7-9-所有关闭swap" aria-hidden="true">#</a> 7.9.所有关闭swap</h2>
<h2 id="_7-10-用kubeadm-初始化集群" tabindex="-1"><a class="header-anchor" href="#_7-10-用kubeadm-初始化集群" aria-hidden="true">#</a> 7.10.用kubeadm 初始化集群</h2>
<h2 id="_7-11-其他节点连接到master节点" tabindex="-1"><a class="header-anchor" href="#_7-11-其他节点连接到master节点" aria-hidden="true">#</a> 7.11.其他节点连接到Master节点</h2>
<h2 id="_7-12-在master节点上查看集群" tabindex="-1"><a class="header-anchor" href="#_7-12-在master节点上查看集群" aria-hidden="true">#</a> 7.12.在master节点上查看集群</h2>
<h2 id="_7-13-安装网络插件" tabindex="-1"><a class="header-anchor" href="#_7-13-安装网络插件" aria-hidden="true">#</a> 7.13.安装网络插件</h2>
<h2 id="_7-14-在master上查看集群节点" tabindex="-1"><a class="header-anchor" href="#_7-14-在master上查看集群节点" aria-hidden="true">#</a> 7.14.在master上查看集群节点</h2>
<h2 id="_7-15-启动故障解决" tabindex="-1"><a class="header-anchor" href="#_7-15-启动故障解决" aria-hidden="true">#</a> 7.15.启动故障解决</h2>
<h2 id="_7-16-基础命令" tabindex="-1"><a class="header-anchor" href="#_7-16-基础命令" aria-hidden="true">#</a> 7.16.基础命令</h2>
<h2 id="_7-17-部署第一个程序到k8s中" tabindex="-1"><a class="header-anchor" href="#_7-17-部署第一个程序到k8s中" aria-hidden="true">#</a> 7.17.部署第一个程序到k8s中</h2>
<h2 id="_7-18-可视化面板kuboard" tabindex="-1"><a class="header-anchor" href="#_7-18-可视化面板kuboard" aria-hidden="true">#</a> 7.18.可视化面板kuboard</h2>
<h1 id="_8-二进制包搭建kubernetes" tabindex="-1"><a class="header-anchor" href="#_8-二进制包搭建kubernetes" aria-hidden="true">#</a> 8.二进制包搭建Kubernetes</h1>
<h2 id="_8-1-环境配置清单" tabindex="-1"><a class="header-anchor" href="#_8-1-环境配置清单" aria-hidden="true">#</a> 8.1.环境配置清单</h2>
<h2 id="_8-2-服务器规划和ip地址规划" tabindex="-1"><a class="header-anchor" href="#_8-2-服务器规划和ip地址规划" aria-hidden="true">#</a> 8.2.服务器规划和IP地址规划</h2>
<h2 id="_8-3-安装前准备工作" tabindex="-1"><a class="header-anchor" href="#_8-3-安装前准备工作" aria-hidden="true">#</a> 8.3.安装前准备工作</h2>
<h2 id="_8-4-安装cfssl证书生成工具" tabindex="-1"><a class="header-anchor" href="#_8-4-安装cfssl证书生成工具" aria-hidden="true">#</a> 8.4.安装cfssl证书生成工具</h2>
<h2 id="_8-5-搭建etcd集群" tabindex="-1"><a class="header-anchor" href="#_8-5-搭建etcd集群" aria-hidden="true">#</a> 8.5.搭建etcd集群</h2>
<h2 id="_8-6-安装配置docker" tabindex="-1"><a class="header-anchor" href="#_8-6-安装配置docker" aria-hidden="true">#</a> 8.6.安装配置Docker</h2>
<h2 id="_8-7-搭建kube-apiserver" tabindex="-1"><a class="header-anchor" href="#_8-7-搭建kube-apiserver" aria-hidden="true">#</a> 8.7.搭建kube-apiserver</h2>
<h2 id="_8-8-在master-node1上部署kube-controller-manager" tabindex="-1"><a class="header-anchor" href="#_8-8-在master-node1上部署kube-controller-manager" aria-hidden="true">#</a> 8.8.在Master Node1上部署kube-controller-manager</h2>
<h2 id="_8-9-部署kube-scheduler" tabindex="-1"><a class="header-anchor" href="#_8-9-部署kube-scheduler" aria-hidden="true">#</a> 8.9.部署kube-scheduler</h2>
<h2 id="_8-10-使用kubectl查看集群状态" tabindex="-1"><a class="header-anchor" href="#_8-10-使用kubectl查看集群状态" aria-hidden="true">#</a> 8.10.使用kubectl查看集群状态</h2>
<h2 id="_8-11-在master-node1上部署第一个worker-node" tabindex="-1"><a class="header-anchor" href="#_8-11-在master-node1上部署第一个worker-node" aria-hidden="true">#</a> 8.11.在Master Node1上部署第一个Worker Node</h2>
<h2 id="_8-12-增加worker-node" tabindex="-1"><a class="header-anchor" href="#_8-12-增加worker-node" aria-hidden="true">#</a> 8.12.增加Worker Node</h2>
<h2 id="_8-13-增加master2节点" tabindex="-1"><a class="header-anchor" href="#_8-13-增加master2节点" aria-hidden="true">#</a> 8.13.增加Master2节点</h2>
<h2 id="_8-14-部署nginx-keepalived高可用负载均衡器" tabindex="-1"><a class="header-anchor" href="#_8-14-部署nginx-keepalived高可用负载均衡器" aria-hidden="true">#</a> 8.14.部署Nginx+Keepalived高可用负载均衡器</h2>
<h2 id="_8-15-部署常见问题" tabindex="-1"><a class="header-anchor" href="#_8-15-部署常见问题" aria-hidden="true">#</a> 8.15.部署常见问题</h2>
<h2 id="_8-16-部署测试程序" tabindex="-1"><a class="header-anchor" href="#_8-16-部署测试程序" aria-hidden="true">#</a> 8.16.部署测试程序</h2>
</div></template>
