server:
  port: 7002 #访问端口
spring:
  application:
    name: SPRINGCLOUD-REGISTER-CENTER-CLUSTER-NODE7002  #注意:服务名不要出现_
  devtools: #热部署工具
    restart:
      enabled: true
eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心,我的职责就是维护实例,不需要去检索服务
    service-url: #把当前eureka7003注册到其他两个注册中心eureka7002、eureka7004中
      defaultZone: http://eureka7003:7003/eureka,http://eureka7004:7004/eureka
  server:
    enable-self-preservation: false #是否开启自我保护,true:服务失效不直接剔除,false:服务失效直接剔除
    eviction-interval-timer-in-ms: 2000 #默认发送心跳的时间间隔,单位为ms