server:
  port: 9527

spring:
  application:
    name: SPRINGCLOUD-ROUTER-CONNECT-DIRECT-CONFIGURATION-GATEWAY9527
  cloud:
    gateway:
      routes:
        #第一个路由,多个路由依靠不同的路由ID区分
        - id: payment_routh   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost          #匹配后提供服务的路由地址
          predicates:
            # 断言，路径相匹配的进行路由,可以匹配下面四个路径:
            # 路径1:http://localhost:9527/consumer/payment/ok/get/{id}
            # 路径2:http://localhost:9527/consumer/payment/timeout/get/{id}
            # 路径3:http://localhost:9527/consumer/payment/degradation_in_provider/get/{id}
            # 路径3:http://localhost:9527/consumer/payment/circuitbreaker/get/{id}
            - Path=/consumer/payment/**/get/**

        #第二个路由,多个路由依靠不同的路由ID区分
        #- id: payment_routh2   #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #  uri: http://localhost          #匹配后提供服务的路由地址
        #  predicates:
        #    - Path=/consumer/payment/**/get/**

eureka:
  instance:
    hostname: ${spring.application.name}
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka


